
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sqlserver
    app.kubernetes.io/component: sqlserver
    app.kubernetes.io/instance: sqlserver
    app.openshift.io/runtime: mssql
    app.openshift.io/runtime-version: 2019-latest
    app.kubernetes.io/part-of: demo-app
  name: sqlserver
spec:
  ports:
  - name: 1433-tcp
    port: 1433
  selector:
    app: sqlserver
    deploymentconfig: sqlserver