apiVersion: v1
data:
  sa_password: cjNkaDR0MSE=
kind: Secret
metadata:
  labels:
    app: sqlserver
    app.kubernetes.io/component: sqlserver
    app.kubernetes.io/instance: sqlserver
    app.openshift.io/runtime: mssql
    app.openshift.io/runtime-version: 2019-latest
  name: sqlserver-sa-password
type: Opaque
